# Generated by Django 4.1.7 on 2023-04-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(blank=True, upload_to='korisnici/profilna/'),
        ),
    ]
