# Generated by Django 4.1.7 on 2023-05-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0002_alter_profil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(blank=True, default='osnova.jpg', upload_to='korisnici/profilna/'),
        ),
    ]
