# Generated by Django 4.1.7 on 2023-04-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glavna', '0002_rename_user_video_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user_name',
            new_name='user',
        ),
    ]
