# Generated by Django 4.1.7 on 2023-04-25 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glavna', '0003_rename_user_name_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glavna.igdb'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
