# Generated by Django 4.1.7 on 2023-03-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glavna', '0005_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
