# Generated by Django 4.1.7 on 2023-05-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavna', '0005_alter_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igdb',
            name='cover_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
