# Generated by Django 4.1.7 on 2023-04-09 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glavna', '0006_delete_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='komentari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=300)),
                ('like', models.BooleanField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='glavna.video')),
            ],
        ),
    ]
