# Generated by Django 4.1.7 on 2023-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavna', '0008_alter_komentari_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentari',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
